[build]
  command = "npm run build"
  publish = "dist"

# Handle single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables can be added in the Netlify dashboard
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Fix for Rollup platform-specific dependencies
[build.processing]
  skip_processing = false
